[project]
name = "oarepo-config"
version = "1.0.1"
description = "Helper library for writing a clean, high-level invenio.cfg for OARepo/Invenio-RDM based repositories"
readme = "README.md"
authors = [
    { name = "Ronald Krist", email = "krist@cesnet.cz" }
]
requires-python = ">=3.14,<3.15"

dependencies = [
    "oarepo[rdm,tests]>=14.2.1b11.dev1,<15.0.0",
]

[project.urls]
Homepage = "https://github.com/oarepo/oarepo-config"

[project.optional-dependencies]
dev = [
    "oarepo-invenio-typing-stubs>=0.1.0dev0,<1.0.0",
    "types-PyYAML",
    "lxml-stubs",
    "oarepo-workflows>=7.0.0,<8.0.0",
    "oarepo-requests>=9.0.0,<10.0.0",
    "oarepo-vocabularies>=9.0.0,<10.0.0",
    "oarepo-oidc-einfra>=7.0.0,<8.0.0",
    "oarepo-glitchtip>=1.3.0,<2.0.0",
    "oarepo-communities>=11.0.0,<12.0.0",
    "oarepo-checks>=2.0.0,<3.0.0",
    "oarepo-dashboard>=8.0.0,<9.0.0",
    "oarepo-doi>=7.0.0,<8.0.0",
    "oarepo-rdm>=8.0.0,<9.0.0",
    "oarepo-related-resources>=4.0.0,<5.0.0"
]
tests = [
    "pytest-invenio>=4.0.0,<5.0.0",
    "pytest-oarepo>=6.0.0,<7.0.0",
]
oarepo14 = [
    "oarepo[rdm,tests]>=14.0.0,<15.0.0",
]
docs = [
    "sphinx>=7.4,<9.0",
    "furo>=2024.8.6",
    "myst-parser>=3.0",
    "sphinx-autobuild>=2024.10.3",
]

[project.entry-points."invenio_config.module"]
0001-invenio_app_rdm = "oarepo_config.initial_rdm_config"
0002-oarepo = "oarepo_config.initial_configuration"

[tool.hatch.build.targets.sdist]
include = [
    "/oarepo_config",
]

[[tool.mypy.overrides]]
follow_untyped_imports = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
